apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: @@-publisher
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: publisher
        target-repo: @@
    spec:
      initContainers:
      - name: initialize-repos
        command:
        - /bin/bash
        - -xc
        - "ORG=$(grep organization: /etc/munge-config/config | cut -d' ' -f2) /publish_scripts/initialize_repos.sh"
        - 2>&1
        image: gcr.io/k8s-testimages/publisher:2016-05-24-86f86cd
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 2000m
          limits:
            cpu: 2000m
        volumeMounts:
        - mountPath: /etc/munge-config
          name: munge-config
        - mountPath: /go-workspace
          name: publisher-gopath
      containers:
      - name: publisher
        command:
        - /mungegithub
        - --dry-run=true
        - --alsologtostderr
        - --config-path=/etc/munge-config/config
        - 2>&1
        image: gcr.io/k8s-testimages/publisher:2016-05-24-86f86cd
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 2000m
          limits:
            cpu: 2000m
        volumeMounts:
        - mountPath: /etc/munge-config
          name: munge-config
        - mountPath: /etc/secret-volume
          name: secret-volume
        - mountPath: /netrc
          name: netrc
        - mountPath: /gitrepos
          name: repo
        - mountPath: /go-workspace
          name: publisher-gopath
      volumes:
      - name: munge-config
        configMap:
          name: @@-publisher-config
      - name: secret-volume
        secret:
          secretName: @@-github-token
      - name: repo
        emptyDir: {}
      - name: netrc
        emptyDir:
          medium: Memory
      - name: publisher-gopath
        persistentVolumeClaim:
          claimName: @@-publisher-gopath
