kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: publisher
    target-repo: kubernetes
  name: kubernetes-publisher-gopath
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ssd
