apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: publisher
    target-repo: @@
  name: @@-publisher-gopath
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: @@-publisher-gopath
    fsType: ext4
  storageClassName: ssd
